/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForCandidatesRouteImport } from './routes/for-candidates'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ForInstitutionsRouteImport } from './routes/for-institutions'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardCredentialsRouteImport } from './routes/dashboard.credentials'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardOrganizationsRouteImport } from './routes/dashboard.organizations'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardVerificationsRouteImport } from './routes/dashboard.verifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCandidatesRoute = ForCandidatesRouteImport.update({
  id: '/for-candidates',
  path: '/for-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForInstitutionsRoute = ForInstitutionsRouteImport.update({
  id: '/for-institutions',
  path: '/for-institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCredentialsRoute = DashboardCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsRoute = DashboardOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerificationsRoute = DashboardVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-institutions': typeof ForInstitutionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-institutions': typeof ForInstitutionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-institutions': typeof ForInstitutionsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/credentials': typeof DashboardCredentialsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/verifications': typeof DashboardVerificationsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-candidates'
    | '/for-employers'
    | '/for-institutions'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/credentials'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/organizations'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/for-candidates'
    | '/for-employers'
    | '/for-institutions'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/credentials'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/organizations'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/for-candidates'
    | '/for-employers'
    | '/for-institutions'
    | '/how-it-works'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/credentials'
    | '/dashboard/documents'
    | '/dashboard/notifications'
    | '/dashboard/organizations'
    | '/dashboard/profile'
    | '/dashboard/verifications'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForCandidatesRoute: typeof ForCandidatesRoute
  ForEmployersRoute: typeof ForEmployersRoute
  ForInstitutionsRoute: typeof ForInstitutionsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-candidates': {
      id: '/for-candidates'
      path: '/for-candidates'
      fullPath: '/for-candidates'
      preLoaderRoute: typeof ForCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-institutions': {
      id: '/for-institutions'
      path: '/for-institutions'
      fullPath: '/for-institutions'
      preLoaderRoute: typeof ForInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credentials': {
      id: '/dashboard/credentials'
      path: '/credentials'
      fullPath: '/dashboard/credentials'
      preLoaderRoute: typeof DashboardCredentialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verifications': {
      id: '/dashboard/verifications'
      path: '/verifications'
      fullPath: '/dashboard/verifications'
      preLoaderRoute: typeof DashboardVerificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCredentialsRoute: typeof DashboardCredentialsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrganizationsRoute: typeof DashboardOrganizationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVerificationsRoute: typeof DashboardVerificationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCredentialsRoute: DashboardCredentialsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrganizationsRoute: DashboardOrganizationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVerificationsRoute: DashboardVerificationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForCandidatesRoute: ForCandidatesRoute,
  ForEmployersRoute: ForEmployersRoute,
  ForInstitutionsRoute: ForInstitutionsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
